### ISSUE TITLE
when preparing the mutcount for each SBS signature, which kinds of filtering for SNP need to be setted

### ISSUE THREAD

**Issue by haixiashang** [QingliGuo/FFPEsig#5]

**Comment by QingliGuo** [comment]
Hi, common SNPs can be filtered using ANNOVAR, vcftools, etc.

**Comment by haixiashang** [comment]
I mean some filtering for all those SNPs, such as allele frequency, and others? When using FFPEsig, only those SNP not annotated by ANNOVAR, vcftools need to be considered  in your pipeline?

**Comment by haixiashang** [comment]
Hello, could you provide me the mutation list of you used in your paper for study 2?

**Comment by QingliGuo** [comment]
FFPEsig assumes the input data is germ-line SNP filtered and focuses on subtracting FFPE artefacts. So, filtering SNP is not part of our pipeline. And I am afraid you need to seek other tools to do so. That's why I recommended the above two methods, and of course, you can try more.

You might have to contact the original authors for the mutation list for study 2 as we do not have the right to share the data (see data availability).

**Comment by haixiashang** [comment]
OK, I know. Thank you very much for your kind reply! Very cool tool!

**Comment by QingliGuo** [comment]
Thanks!
